### ISSUE TITLE
Setting a port leads to Fatal error with escapeshellarg (possibly only with strict typing?)

### ISSUE THREAD

**Issue by YetiCGN** [TYPO3/Surf#627]
## Expected Behavior
```
$node
    ->setHostname('ip-address as string')
    ->setPort(2222) // Port number as int as per method argument typing
...
```

Expected: Deployment runs without error

## Actual Behavior
```
PHP Fatal error:  Uncaught TypeError: escapeshellarg() expects parameter 1 to be string, int given 
in /my/project/dir/vendor/typo3/surf/src/Task/Transfer/RsyncTask.php:55
```

## Steps to Reproduce the Problem
  1. Use `<?php declare(strict_types=1);` in deployment script
  1. Set a port on the node
  1. Run deployment

## Specifications

  - Surf Version: 3.3.4
  - Application: TYPO3 10.4.32
  - PHP Version: 7.4.32
  - Platform: Ubuntu Linux 20.04.5 LTS (through WSL 1)
  - Environment (CI): local
  - Deployment configuration: TYPO3\Surf\Application\TYPO3\CMS

**Comment by YetiCGN** [comment]
Already fixed in 8a51ce7d, please release.

**Comment by martinlipp** [comment]
The same still happens in the Neos/Flow/CopyConfigurationTask, lines 62 and 63:
https://github.com/TYPO3/Surf/blob/9edbb19cb478c71a2b1d1cc7ffc860cbbcec21d6/src/Task/Neos/Flow/CopyConfigurationTask.php#L62

Let me know if I should create a separate issue for this.
